services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile-local
    command: python backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app/backend
      - ./common:/app/common
      - ./config.yml:/app/config/config.yml:ro
      - ./templates:/app/templates
      - ./common/logs:/app/logs
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
